[settings]
sops.age_key_file = ".secrets/mise-age.txt"
sops.rops = false                           # use original SOPS binary not a rops library
sops.strict = false                         # if age key is not provided do not raise an ERROR

[[env]]
MISE_SOPS_AGE_KEY_FILE = ".secrets/mise-age.txt"
SOPS_AGE_KEY_FILE = "{{env.MISE_SOPS_AGE_KEY_FILE}}"

[[env]]
_.file = [".env.secrets.json"]

[tools]
age = "latest"
sops = "latest"

[tasks.secrets-edit]
description = "Edit encrypted secrets file"
run = ["sops .env.secrets.json"]

