[tools]
# Git hooks manager
lefthook = "2.1.1"

[settings]
experimental = true # enable hooks

[hooks]
# NOTE: to make tasks names printed nice, stay with 16 chars task name for hook tasks
enter = ["mise run install-githooks"]

[tasks.install-githooks]
description = "Install git hooks with lefthook help"
run = ["lefthook install"]
