[settings]
experimental = true

[tasks.full-env-prepare]
description = "Pre-configure project folders and tools"
run = ["./scripts/00-setup-project.sh"]

[hooks]
# NOTE: to make tasks names printed nice, stay with 16 chars task name for hook tasks
enter = ["mise run full-env-prepare"]
